p8105_hw2_nt2607
================
Niharika Telrandhe
2022-10-05

## Problem 1

**This problem focuses on NYC Transit data.**

``` r
nyctransit_df = 
  read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(line, starts_with('station'),starts_with('route'), entry, vending, entrance_type, ada, -station_location) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
summary(nyctransit_df)
```

    ##      line           station_name       station_latitude station_longitude
    ##  Length:1868        Length:1868        Min.   :40.58    Min.   :-74.03   
    ##  Class :character   Class :character   1st Qu.:40.69    1st Qu.:-73.99   
    ##  Mode  :character   Mode  :character   Median :40.73    Median :-73.96   
    ##                                        Mean   :40.73    Mean   :-73.94   
    ##                                        3rd Qu.:40.77    3rd Qu.:-73.91   
    ##                                        Max.   :40.90    Max.   :-73.76   
    ##     route1             route2             route3             route4         
    ##  Length:1868        Length:1868        Length:1868        Length:1868       
    ##  Class :character   Class :character   Class :character   Class :character  
    ##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
    ##                                                                             
    ##                                                                             
    ##                                                                             
    ##     route5             route6             route7             route8         
    ##  Length:1868        Length:1868        Length:1868        Length:1868       
    ##  Class :character   Class :character   Class :character   Class :character  
    ##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
    ##                                                                             
    ##                                                                             
    ##                                                                             
    ##     route9            route10            route11            entry        
    ##  Length:1868        Length:1868        Length:1868        Mode :logical  
    ##  Class :character   Class :character   Class :character   FALSE:115      
    ##  Mode  :character   Mode  :character   Mode  :character   TRUE :1753     
    ##                                                                          
    ##                                                                          
    ##                                                                          
    ##    vending          entrance_type         ada         
    ##  Length:1868        Length:1868        Mode :logical  
    ##  Class :character   Class :character   FALSE:1400     
    ##  Mode  :character   Mode  :character   TRUE :468      
    ##                                                       
    ##                                                       
    ## 

## Short paragraph about the dataset

This dataset contains the following variables : line, station_name,
station_latitude, station_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entry,
vending, entrance_type, ada

My data cleaning steps involved importing the dataset, cleaning of
variable names, selecting particular variables and converting the entry
variable from character to logical.

The dimensions of the resulting dataset are 1868, 19

Yes, these data are tidy.

## Answer the following questions using this data

*How many distinct stations are there?* There are 465 distinct stations.

``` r
nrow(distinct(nyctransit_df, line, station_name))
```

    ## [1] 465

*How many stations are ADA compliant?* There are 468 stations that are
ADA compliant.

``` r
nrow(filter(nyctransit_df, ada == TRUE))
```

    ## [1] 468

*What proportion of station entrances / exits without vending allow
entrance?*

``` r
without_vending = nrow(filter(nyctransit_df, vending == 'NO'))
without_vending
```

    ## [1] 183

``` r
entry_no_vending = nrow(filter(nyctransit_df, vending == 'NO', entry == 'TRUE'))
entry_no_vending
```

    ## [1] 69

``` r
Proportion = entry_no_vending/without_vending
Proportion
```

    ## [1] 0.3770492

*Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train? Of the stations
that serve the A train, how many are ADA compliant?*

``` r
nyctransit_df %>%
  pivot_longer(
    route1:route11,
    names_to = "route_names",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
nyctransit_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_names",
    values_to = "route") %>% 
   filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

## Problem 2

**Read and clean the Mr. Trash Wheel sheet:**

``` r
mr_trash_df = read_excel("./data/Trash Wheel Collection Data.xlsx",
sheet = "Mr. Trash Wheel",
range = "A2:N549") %>%
  janitor::clean_names() %>% 
  drop_na(dumpster)
```

## Problem 3

**First, clean the data in pols-month.csv.**

``` r
pols_month_df = read.csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(.data = ., month = as.integer(month),
          month = month.name[month],
          year = as.integer(year),
         day = as.integer(day),
         president = case_when(prez_dem =="1" ~ "dem",
                               prez_gop == "1" ~ "gop"
          )) %>% 
  select(-day, -prez_dem, -prez_gop)
head(pols_month_df)
```

    ##   year    month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ## 1 1947  January      23      51     253      23      45     198       dem
    ## 2 1947 February      23      51     253      23      45     198       dem
    ## 3 1947    March      23      51     253      23      45     198       dem
    ## 4 1947    April      23      51     253      23      45     198       dem
    ## 5 1947      May      23      51     253      23      45     198       dem
    ## 6 1947     June      23      51     253      23      45     198       dem

Note: The variable prez_gop should only accept 0 or 1 but i can see a
few 2’s as well which make cause errors.

**Cleaning the data in snp.csv**

``` r
snp_df = read.csv("./data/fivethirtyeight_datasets/snp.csv") %>%
janitor::clean_names() %>%
  mutate(date = lubridate::mdy(date)) %>%
  separate(date, into = c("year","month","day"), convert = TRUE) %>%
  mutate(month = as.integer(month),
         month = month.name[month],
         year = as.integer(year),
         day = as.integer(day)) %>% 
  select(-day) %>% 
  arrange(year, month) %>% 
  relocate(year, month, close)
head(snp_df)
```

    ##   year    month  close
    ## 1 1969    April 103.69
    ## 2 1969   August  95.51
    ## 3 1969 December  92.06
    ## 4 1969 February  98.13
    ## 5 1969  January 103.01
    ## 6 1969     July  91.83

**Cleaning the data in unemployment.csv**

``` r
unemployment_df = read.csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>%
  pivot_longer( jan:dec,
                names_to = "month",
                values_to = "unemployment_rate") %>% 
  mutate(year = as.numeric(year),
         month = recode(month,
                        jan = "January",
                        feb = "February",
                        mar = "March",
                        apr = "April",
                        may = "May",
                        jun = "June",
                        jul = "July",
                        aug = "August",
                        sep = "September",
                        oct = "October",
                        nov = "November",
                        dec = "December"))
head(unemployment_df)
```

    ## # A tibble: 6 × 3
    ##    year month    unemployment_rate
    ##   <dbl> <chr>                <dbl>
    ## 1  1948 January                3.4
    ## 2  1948 February               3.8
    ## 3  1948 March                  4  
    ## 4  1948 April                  3.9
    ## 5  1948 May                    3.5
    ## 6  1948 June                   3.6

**Merging**

``` r
join = left_join(pols_month_df, snp_df, by = c("year","month")) %>%
  left_join(unemployment_df, by = c("year", "month"))
```

**Description**

In the `pols_month_df` dataset we have 822 rows and 9 columns.

In the `snp_df` dataset we have 787 rows and 3 columns.
